---
- name: Playbook - Install figlet cowsay bastet   # metadata
  hosts: planetexpress:!bender !farnsworth   # we want to take the planetexpress group and remove farnsworth
  connection: ssh     # default is to use the connection plugin ssh.py
  gather_facts: yes   # default is yes

  tasks:                             # a list of what we want to do 
  - name: using apt to install figlet cowsay and bastet  # metadata
    apt:                     # the module we want to run, apt.py
#        pkg:
        name:
        - figlet
        - cowsay
        - bastet
        state: absent
    become: True              # elevate status to admin, sudo, enable, etc.


