---
- name: Playbook - Remove bastet    # metadata
  hosts: planetexpress:!bender !farnsworth   # we want to take the planetexpress group and remove farnsworth
  connection: ssh     # default is to use the connection plugin ssh.py
  gather_facts: yes   # default is yes

  tasks:                             # a list of what we want to do 
  - name: using apt to remove bastet  # metadata
    apt:                     # the module we want to run, apt.py
        name: bastet         # parameter name has the value bastet
        state: absent       # parameter state has the value present
    become: yes              # elevate status to admin, sudo, enable, etc.
