---
- name: Copying content from controller to hosts
  hosts: planetexpress:!farnsworth
  gather_facts: yes # default is yes

  tasks:
    - name: Copy gather fact var data into hosts
      copy:
#        content: "{{ ansible_all_ipv4_addresses }}" # facts gathered from host
#        content: "{{ ansible_all_ipv4_addresses.0 }}" # facts gathered from host  .0 removes braces, could also use [0]
        content: "{{ ansible_all_ipv4_addresses[0] }}" # facts gathered from host  .0 removes braces, could also use [0]
        dest: ~/ipv4info.txt      # home directory on hosts
        backup: yes   # make backup of original
        force: yes    # file always copied when content is diff

