---
- name: Make sure packages are up to date
  package:
    name:
      - sl
      - cowsay  
      - figlet
#      -bastet
    state: latest
  become: True

- name: Make sure bastet is up to date
  package:
    name: bastet
    state: latest
  become: True
  when: ansible_distribution ==  "Ubuntu"

- name: Add a log entry
  lineinfile:
    path: ~/loggy.log
    line:  "{{ ansible_date_time.iso8601 }} - Passed Checkup"
#    line:  "{{ ansible_date_time }} - Passed Checkup"
#    line:  "{{ ansible_date_time.date }} - Passed Checkup"
    create: True

